version: '2'
services:
  glossary-service:
    build: .
    ports:
      - '4000:4000'
    volumes:
      - .:/home/node/
      - /home/node/node_modules
    environment: 
      MONGO_URL: mongo-db:27017

  mongo-db:
    image: mongo
    restart: always

volumes:
  mongo: